# Level 3 — Business Analytics

## Objective

This notebook answers business questions using SQL queries and summarizes insights for stakeholders.

In [2]:
import duckdb

con = duckdb.connect()

con.execute("""
CREATE OR REPLACE VIEW superstore_features AS
SELECT *
FROM read_csv_auto('../data/superstore_features.csv');
""")

### Do Product Prices Differ Across Customer Segments?

Average unit prices and discounts were compared across customer segments to determine whether pricing patterns differed between Consumer, Corporate, and Home Office customers.

In [4]:
con.execute('''
SELECT 
    product_id,
    segment,
    ROUND(AVG(sales / quantity), 2) AS avg_unit_price,
    ROUND(AVG(discount), 3) AS avg_discount
FROM superstore_features
GROUP BY product_id, segment
ORDER BY product_id
Limit 40''').df()

         product_id      segment  avg_unit_price  avg_discount
0   FUR-BO-10000112    Corporate           91.69         0.300
1   FUR-BO-10000330     Consumer          111.91         0.075
2   FUR-BO-10000330  Home Office          102.83         0.150
3   FUR-BO-10000362     Consumer          136.78         0.200
4   FUR-BO-10000362    Corporate          158.16         0.075
5   FUR-BO-10000362  Home Office          145.33         0.150
6   FUR-BO-10000468    Corporate           48.58         0.000
7   FUR-BO-10000468     Consumer           37.89         0.220
8   FUR-BO-10000711     Consumer           70.98         0.000
9   FUR-BO-10000711  Home Office           70.98         0.000
10  FUR-BO-10000780     Consumer          133.65         0.335
11  FUR-BO-10000780    Corporate          136.67         0.320
12  FUR-BO-10001337     Consumer          107.87         0.108
13  FUR-BO-10001337    Corporate          108.88         0.100
14  FUR-BO-10001337  Home Office          102.83         0.150
15  FUR-BO-10001519     Consumer           48.45         0.167
16  FUR-BO-10001519  Home Office           49.42         0.150
17  FUR-BO-10001519    Corporate           46.51         0.200
18  FUR-BO-10001567    Corporate           30.29         0.700
19  FUR-BO-10001601    Corporate           89.07         0.320
20  FUR-BO-10001601     Consumer          111.33         0.150
21  FUR-BO-10001601  Home Office           89.07         0.320
22  FUR-BO-10001608     Consumer           49.33         0.305
23  FUR-BO-10001608    Corporate           70.98         0.000
24  FUR-BO-10001619  Home Office           76.48         0.100
25  FUR-BO-10001798     Consumer          103.15         0.213
26  FUR-BO-10001811     Consumer          205.96         0.316
27  FUR-BO-10001811    Corporate          204.67         0.320
28  FUR-BO-10001918    Corporate          108.66         0.325
29  FUR-BO-10001918     Consumer          128.78         0.200
30  FUR-BO-10001972  Home Office          108.88         0.100
31  FUR-BO-10001972    Corporate           48.39         0.600
32  FUR-BO-10001972     Consumer           58.47         0.517
33  FUR-BO-10002202     Consumer          118.08         0.510
34  FUR-BO-10002206     Consumer          119.83         0.150
35  FUR-BO-10002213     Consumer          294.82         0.160
36  FUR-BO-10002268    Corporate           55.07         0.320
37  FUR-BO-10002268     Consumer           44.54         0.450
38  FUR-BO-10002545    Corporate          218.57         0.163
39  FUR-BO-10002545     Consumer          221.83         0.150

In [7]:
con.execute ("""
SELECT 
    segment,
    COUNT(DISTINCT customer_name) AS customer_count,
    ROUND(SUM(sales)) AS total_sales
FROM superstore_features
GROUP BY segment
""").df()

       segment  customer_count  total_sales
0  Home Office             148     429653.0
1     Consumer             409    1161401.0
2    Corporate             236     706146.0

In [8]:
con.execute('''
SELECT
    product_id,
    segment,
    ROUND(AVG(sales / quantity), 2) AS avg_unit_price,
    ROUND(AVG(discount), 3) AS avg_discount
FROM superstore_features
GROUP BY product_id, segment
ORDER BY product_id
LIMIT 40;
''').df()

         product_id      segment  avg_unit_price  avg_discount
0   FUR-BO-10000112    Corporate           91.69         0.300
1   FUR-BO-10000330     Consumer          111.91         0.075
2   FUR-BO-10000330  Home Office          102.83         0.150
3   FUR-BO-10000362     Consumer          136.78         0.200
4   FUR-BO-10000362    Corporate          158.16         0.075
5   FUR-BO-10000362  Home Office          145.33         0.150
6   FUR-BO-10000468    Corporate           48.58         0.000
7   FUR-BO-10000468     Consumer           37.89         0.220
8   FUR-BO-10000711  Home Office           70.98         0.000
9   FUR-BO-10000711     Consumer           70.98         0.000
10  FUR-BO-10000780     Consumer          133.65         0.335
11  FUR-BO-10000780    Corporate          136.67         0.320
12  FUR-BO-10001337  Home Office          102.83         0.150
13  FUR-BO-10001337     Consumer          107.87         0.108
14  FUR-BO-10001337    Corporate          108.88         0.100
15  FUR-BO-10001519    Corporate           46.51         0.200
16  FUR-BO-10001519     Consumer           48.45         0.167
17  FUR-BO-10001519  Home Office           49.42         0.150
18  FUR-BO-10001567    Corporate           30.29         0.700
19  FUR-BO-10001601    Corporate           89.07         0.320
20  FUR-BO-10001601     Consumer          111.33         0.150
21  FUR-BO-10001601  Home Office           89.07         0.320
22  FUR-BO-10001608     Consumer           49.33         0.305
23  FUR-BO-10001608    Corporate           70.98         0.000
24  FUR-BO-10001619  Home Office           76.48         0.100
25  FUR-BO-10001798     Consumer          103.15         0.213
26  FUR-BO-10001811     Consumer          205.96         0.316
27  FUR-BO-10001811    Corporate          204.67         0.320
28  FUR-BO-10001918    Corporate          108.66         0.325
29  FUR-BO-10001918     Consumer          128.78         0.200
30  FUR-BO-10001972  Home Office          108.88         0.100
31  FUR-BO-10001972    Corporate           48.39         0.600
32  FUR-BO-10001972     Consumer           58.47         0.517
33  FUR-BO-10002202     Consumer          118.08         0.510
34  FUR-BO-10002206     Consumer          119.83         0.150
35  FUR-BO-10002213     Consumer          294.82         0.160
36  FUR-BO-10002268     Consumer           44.54         0.450
37  FUR-BO-10002268    Corporate           55.07         0.320
38  FUR-BO-10002545    Corporate          218.57         0.163
39  FUR-BO-10002545  Home Office          193.13         0.260

In [9]:
con.execute('''
SELECT
    segment,
    ROUND(AVG(fulfillment_days),2) AS avg_fulfillment_days,
    MIN(fulfillment_days) AS min_days,
    MEDIAN(fulfillment_days) AS median_days,
    MAX(fulfillment_days) AS max_days
FROM superstore_features
GROUP BY segment
ORDER BY avg_fulfillment_days;
''').df()

       segment  avg_fulfillment_days  min_days  median_days  max_days
0  Home Office                  3.92         0          4.0         7
1     Consumer                  3.94         0          4.0         7
2    Corporate                  4.01         0          4.0         7

In [ ]:
con.execute("""
SELECT
    ship_mode,
    ROUND(AVG(fulfillment_days), 2) AS avg_fulfillment_days,
    MIN(fulfillment_days) AS min_days,
    MAX(fulfillment_days) AS max_days
FROM superstore_features
GROUP BY ship_mode
ORDER BY avg_fulfillment_days;
""").df()

extra stuff to think about:

In [10]:
con.execute(''' 
SELECT
    product_name,
    sales,
    profit,
    profit_margin
FROM superstore_features
ORDER BY profit_margin
LIMIT 10
''').df()

,product_name,sales,profit,profit_margin
0,Kensington 6 Outlet SmartSocket Surge Protector,24.588,-67.6170,-2.75
1,Eureka Disposable Bags for Sanitaire Vibra Gro...,1.624,-4.4660,-2.75
2,Hoover Portapower Portable Vacuum,2.688,-7.3920,-2.75
3,Hoover Shoulder Vac Commercial Portable Vacuum,143.128,-393.6020,-2.75
4,Euro Pro Shark Stick Mini Vacuum,48.784,-131.7168,-2.70
5,Acco Smartsocket Color-Coded Six-Outlet AC Ada...,26.406,-71.2962,-2.70
6,Tripp Lite Isotel 8 Ultra 8 Outlet Metal Surge,70.970,-191.6190,-2.70
7,Fellowes 8 Outlet Superior Workstation Surge P...,33.620,-90.7740,-2.70
8,Belkin 6 Outlet Metallic Surge Strip,4.356,-11.7612,-2.70
9,Hoover Commercial Lightweight Upright Vacuum,1.392,-3.7584,-2.70